### ISSUE TITLE
error python high version

### ISSUE THREAD

**Issue by bejokun** [drunkdream/turbo-tunnel#87]
turbo-tunnel
Traceback (most recent call last):
  File "/usr/local/bin/turbo-tunnel", line 5, in <module>
    from turbo_tunnel.__main__ import main
  File "/usr/local/lib/python3.10/dist-packages/turbo_tunnel/__init__.py", line 27, in <module>
    from . import ssh
  File "/usr/local/lib/python3.10/dist-packages/turbo_tunnel/ssh.py", line 15, in <module>
    import asyncssh
  File "/usr/local/lib/python3.10/dist-packages/asyncssh/__init__.py", line 31, in <module>
    from .agent import SSHAgentClient, SSHAgentKeyPair, connect_agent
  File "/usr/local/lib/python3.10/dist-packages/asyncssh/agent.py", line 30, in <module>
    from .public_key import SSHKeyPair, load_default_keypairs, load_keypairs
  File "/usr/local/lib/python3.10/dist-packages/asyncssh/public_key.py", line 32, in <module>
    from .crypto import ed25519_available, ed448_available
  File "/usr/local/lib/python3.10/dist-packages/asyncssh/crypto/__init__.py", line 50, in <module>
    from .x509 import X509Name, X509NamePattern
  File "/usr/local/lib/python3.10/dist-packages/asyncssh/crypto/x509.py", line 33, in <module>
    from OpenSSL import crypto
  File "/usr/local/lib/python3.10/dist-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import SSL, crypto
  File "/usr/local/lib/python3.10/dist-packages/OpenSSL/SSL.py", line 34, in <module>
    from OpenSSL.crypto import (
  File "/usr/local/lib/python3.10/dist-packages/OpenSSL/crypto.py", line 945, in <module>
    utils.deprecated(
TypeError: deprecated() got an unexpected keyword argument 'name'
root@direk-fra1-3:~# python3 -V
Python 3.10.12

**Comment by drunkdream** [comment]
It looks like the dependency library has conflict, i test python 3.11 is ok, can you test in virtual python environment?

**Comment by bejokun** [comment]
yes its working perfectly with venv
